### PR TITLE
chore: add pretty-quick to the dev dependencies

### PR DESCRIPTION
**Pull request by jrenee42**
no bug number...just improving the code.  

pretty-quick is MUCH easier to use than prettier.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 51 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

**Comment by genehynson** [comment]
Nice! Can we also remove `prettier` from `package.json`?

**Review by hoorayimhelping — COMMENTED** [review]
do we need to hook up the [prettier script command](https://github.com/influxdata/ui/blob/master/package.json#L45-L46) in package.json to pretty-quick?

**Comment by jrenee42** [comment]
@genehynson  and @hoorayimhelping:

are you talking  about replacing:
` "lint": "yarn tsc && yarn prettier && yarn eslint",`

with: 
` "lint": "yarn tsc && yarn pretty-quick && yarn eslint",`

if so, then it would run quicker.

I can try that in the morning and see how it goes.

**Comment by hoorayimhelping** [comment]
@jrenee42 not exactly, but close. I'm talking about changing this:

```json
"prettier": "prettier --config .prettierrc.json --check '{src,cypress}/**/*.{ts,tsx}'",
"prettier:fix": "prettier --config .prettierrc.json --write '{src,cypress}/**/*.{ts,tsx}'",
```

to 
```json
"prettier": "pretty-quick --config .prettierrc.json --check '{src,cypress}/**/*.{ts,tsx}'",
"prettier:fix": "pretty-quick --config .prettierrc.json --write '{src,cypress}/**/*.{ts,tsx}'",
```

which would automatically fix any calls to ```yarn prettier```

**Comment by jrenee42** [comment]
so I put in the changes that @hoorayimhelping  suggested (in package.json); and the effects are:
1) when you run `yarn prettier:fix` in the command line, it now runs pretty-quick instead
2) no changes to the build; the 'install dependencies' part of the unit tests still uses prettier:
Screen Shot 2021-02-04 at 11 21 27 AM

so @hoorayimhelping  ready for your review again.

**Comment by jrenee42** [comment]
the circle ci is actually done successfully: https://app.circleci.com/pipelines/github/influxdata/ui?branch=chore%2Fadd-pretty-quick

antd the semantic stuff is all good (it's all chore: <stuff>).

so ready to review @hoorayimhelping  for reals :)

**Review by hoorayimhelping — APPROVED** [review]

**Pull request merged**
