### PR TITLE
chore: upgrades immer to 9.0.3 (latest)

### PR DESCRIPTION
**Pull request by genehynson**
The final step on the journey of upgrading immer. This PR bumps it to 9.0.3 which is the latest version.

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 55 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

**Comment by genehynson** [comment]
ok so this breaks EVERYTHING. cool 😅

**Comment by Asalem1** [comment]
Should we bump to 8 and check out the change log for breaking changes between the two major releases?

**Comment by genehynson** [comment]
The changes made in the PR bumping Immer to v8 seemed to help with this version as well: https://github.com/influxdata/ui/pull/1753

**Comment by Asalem1** [comment]
So long as we aren't using "recipes" then that sounds good to me

**Review by Asalem1 — APPROVED** [review]

**Pull request merged**
