### PR TITLE
chore: update vwo smartcode

### PR DESCRIPTION
**Pull request by mavarius**
Addresses https://github.com/influxdata/idpe/issues/16543

This PR updates the version of the VWO smartcode to v1.5

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change

### CODE REVIEW

**Comment by wdoconnell** [comment]
@mavarius Is this needed to take advantage of new VWO features?

**Comment by mavarius** [comment]
> @mavarius Is this needed to take advantage of new VWO features?

No, this is to address the security vulnerability outlined in https://github.com/influxdata/idpe/issues/16543.

**Comment by wdoconnell** [comment]
@mavarius Thanks - has VWO updated the code on their end to ensure it isn't using the deprecated jquery version?

**Comment by wdoconnell** [comment]
The critical thing here is ensuring that our patch to resolve the "black screen of death" issue still works - namely that in `src/App.tsx`, we are still removing the correct style as a fallback in the event that the VWO script fails like it did a couple months ago. It looks like to be same style name (`_vis_opt_path_hides`), which is good. I don't love having to use third-party code like this that is already difficult to understand, but I get why we need to given the IDPE issue.

If we run into issues with the upgraded script, the first line of defense is to flip the flag `vwoAbTesting` off in ConfigCat to troubleshoot any issues with the scritp.

**Comment by mavarius** [comment]
@wdoconnell I noticed that these two rules were removed in the previous implementation, so I removed them here again. Maybe they were part of what caused the black screen issue last time.

```
hide_element='body',
hide_element_style = 'opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important',
```

**Review by wdoconnell — APPROVED** [review]

**Pull request merged**
