### PR TITLE
test: turn on annotations tests

### PR DESCRIPTION
**Pull request by hoorayimhelping**
connects https://github.com/influxdata/ui/issues/2012

Turns back on annotations and skips the couple of flaky ones while'st we work on a fix

### CODE REVIEW

**Review by TCL735 — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 52 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2040)

**Review by genehynson — COMMENTED** [review]
Do we have an issue for fixing and re-enabling these skipped tests?

**Comment by hoorayimhelping** [comment]
https://github.com/influxdata/ui/issues/2012

**Comment by genehynson** [comment]
> #2012

Can we call out the skipped tests in this PR specifically in #2012 ? Just don't want to forget about them or why we skipped them to begin with 😄

**Review by genehynson — APPROVED** [review]

**Comment by hoorayimhelping** [comment]
@genehynson 

I updated the ticket like you asked, but I assure you we won't forget about them. Jill is actively working on a UX improvement that will address the 3/4 skipped tests and I just realized we can delete the last one since we have tests that do the same thing.

**Comment by genehynson** [comment]
fantastic! thanks @hoorayimhelping ! 🙌

**Pull request merged**
