### PR TITLE
chore: updating giraffe version for easier annotation editing

### LINKED ISSUE #1119: When hover legend is long, it's really hard to click on the annotation
I have a graph with a very long tooltip.  When I try to select the annotation, it's hard to select it because the tooltip gets in the way.  See screenshot (or you can see it in the tools cluster in Barbara's test dashboard, on the Api Request Totals cell.
Screen Shot 2021-04-05 at 12 28 13 PM

### PR DESCRIPTION
**Pull request by jrenee42**
Closes #1119 
anno

### CODE REVIEW

**Comment by hoorayimhelping** [comment]
@jrenee42 a picture is worth a thousand words! Show us what it looks like!

**Review by hoorayimhelping — APPROVED** [review]
I noticed that on range annotations, the tooltip showed up when you hover over range annotations. I don't think it's worth blocking at all, but wanted to call it out.

**Comment by jrenee42** [comment]
> I noticed that on range annotations, the tooltip showed up when you hover over range annotations. I don't think it's worth blocking at all, but wanted to call it out.

it's supposed to show up (the tooltip for the annotation)
so all good.
but we can do a call later to clarify expected behavoir

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 50 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2064)

**Pull request merged**
