### PR TITLE
refactor: use new DateFormatter for FunctionRunLogRow

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
closes: #1905

Replaces the `moment` library with the new `DateFormatter` in `FunctionRunLogRow`.

_Screenshots coming soon_

### CODE REVIEW

**Comment by hoorayimhelping** [comment]
@ChitlangeSahas thanks for taking this on! Can you write a small ticket for this please? and could you also include a screenshot of where this is used?

**Comment by ChitlangeSahas** [comment]
@hoorayimhelping Yes, absolutely, I'll write an issue and update the screenshots!

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 58 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

**Review by hoorayimhelping — APPROVED** [review]
Thanks for taking care of this - since this is feature flagged and experimental, it's pretty low risk.

**Pull request merged**
