### PR TITLE
chore: mop up an openapi change that was made without consultation

### PR DESCRIPTION
**Pull request by TCL735**
Mopping up after this change: https://github.com/influxdata/openapi/pull/116

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 46 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=1685)

**Review by Asalem1 — CHANGES_REQUESTED** [review]
I'm a little reluctant on this one since it's weird that the openAPI change to update the SHA wouldn't have thrown a TS error to prevent this from getting in in the first place. What exactly is the issue here?

**Comment by Asalem1** [comment]
Follow up on the original comment, after some investigating it seems like the UI is expecting specific types that aren't in that openAPI contract. We should either update the yaml so that the contract reflects the UI expectations, or update the UI so that it's based off of the API contract. Either way, we need to make sure that there's one source of truth here for what a telegraf plugin type can be, and go based off of that.

**Comment by TCL735** [comment]
Openapi changes got reverted. No need for this anymore.

**Pull request closed without merging**
