### PR TITLE
fix: fix context menu styling and scroll bar issue

### LINKED ISSUE #3187: Tokens: Update Context menu for tokens
The resource card styling has changed, so the context menu needs updating and the tests needs updating as well.

### LINKED ISSUE #3205: Scroll bar style issue on tokens
Tokens scroll bar ever expands

https://images.zenhubusercontent.com/279622976/c871ecf9-4811-4d49-8385-1aef5a205a9f/screen_recording_2021_11_10_at_3_25_23_pm.mov

### PR DESCRIPTION
**Pull request by daviddkkim**
Closes #3187 
Closes #3205

https://user-images.githubusercontent.com/12561526/141204233-5ee57060-9812-4e8e-8c3e-9801e0e7fbb3.mov

^ This is what it used to do 

Below is what it does now

https://user-images.githubusercontent.com/12561526/141204345-acbd5ac9-9125-489c-be04-0ce3fce6b77c.mp4

and here's the new context menu

Screen Shot 2021-11-10 at 5 31 43 PM

Deprecate old context menu

fix scroll bar expansion

### CODE REVIEW

**Comment by hoorayimhelping** [comment]
@daviddkkim would you mind adding a screenshot or a video to this?

**Comment by daviddkkim** [comment]
> @daviddkkim would you mind adding a screenshot or a video to this?

coming!

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3206)

**Review by hoorayimhelping — APPROVED** [review]
looks good to me! But let's give @Palakp41 a chance to weigh in since she's leading this epic before merging in

**Review by blegesse-git — APPROVED** [review]

**Review by Palakp41 — APPROVED** [review]

**Pull request merged**
