### PR TITLE
chore(deps): bump influxdata/influxdb-templates from 0.11.0 to 0.12.0

### PR DESCRIPTION
**Pull request by bednar**
Related to https://github.com/influxdata/edge/issues/751

This PR updates `influxdb-templates` to the latest version, which includes security updates for the `rollup` dependency.

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by bednar** [comment]
I’ve successfully tested the new version of the influxdb-templates by importing the ‘InfluxDB Open Source (OSS) Metrics Template’ during the onboarding setup of InfluxDB.

Is there a way to test other templates listed at [this component](https://github.com/influxdata/ui/blob/b70964631094254ac39edc50951601414c24f6d8/src/templates/constants/defaultTemplates.ts#L32)? Unfortunately, I wasn’t able to locate them in the UI.

**Review by wdoconnell — APPROVED** [review]
Reviewed the related Edge ticket - thank you for linking it.

**Comment by wdoconnell** [comment]
> I’ve successfully tested the new version of the influxdb-templates by importing the ‘InfluxDB Open Source (OSS) Metrics Template’ during the onboarding setup of InfluxDB.
> 
> Is there a way to test other templates listed at [this component](https://github.com/influxdata/ui/blob/b70964631094254ac39edc50951601414c24f6d8/src/templates/constants/defaultTemplates.ts#L32)? Unfortunately, I wasn’t able to locate them in the UI.

Not so familiar with that, but I'm happy to review it when back in-office on Tuesday.

**Comment by wdoconnell** [comment]
@bednar Won't block this based on the Edge discussion, but can we wait until Tuesday to merge?

**Comment by bednar** [comment]
@wdoconnell, of course, it can wait until Tuesday. Could you merge this PR when it’s convenient for you? After that, I will proceed with PRs for InfluxDB to finish https://github.com/influxdata/edge/issues/751

**Comment by bednar** [comment]
@wdoconnell, is it okay to merge this PR now?

**Comment by wdoconnell** [comment]
@bednar Yes, please feel free to merge.

**Comment by wdoconnell** [comment]
Remerging, as it flaked.

**Pull request merged**
