### PR TITLE
chore: don't send feature flags on appMetrics requests

### LINKED ISSUE #2277: App Metrics: Don't send feature flag state on requests
### Background
We recently had a storage issue in cloud relating to the number of tags sent. The bug has since been fixed, but this highlighted the issue that we're sending over too much data. After checking with the folks who used our app-metrics data, we figured out that not many people care about the flag state, so let's remove it.

### Acceptance Criteria
- Don't send the user's flags across the wire in app metrics

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #2277 

We're sending too much information across the wire. The flags data wasn't being used by any system consuming application metrics.

### CODE REVIEW

**Review by Asalem1 — COMMENTED** [review]
I'm a little confused. I think we do use this to track the events and how they compare when a feature is toggled on and off. I defer to @drdelambre on that since he may have more context on that.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2288)

**Review by TCL735 — APPROVED** [review]

**Review by drdelambre — CHANGES_REQUESTED** [review]
i need flags

**Comment by drdelambre** [comment]
yeah, i'm confused as well. i'm using them to track how well a feature flag is doing WoW and distingguishing when a flag was turned on vs when a user actually picked up the changes, and they get consumed in GA for setting up funnels, but more specifically there is a developing conversation with product that puts feature flags not just as switches to revert bad code, but to run experiments, where we are running 25% with a flag on and 75% off. we need this information to distinguish conversion funnel results on either side of that divide. is there a specific system that isn't scaling properly with these?

**Comment by hoorayimhelping** [comment]
these are in fact needed, so I'm closing this PR.

**Pull request closed without merging**
