### PR TITLE
fix: page content now visible on mobile devices

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
Closes https://github.com/influxdata/ui/issues/5645

App works on mobile now as well. 

Clockface was behaving weird with the `div` in the App.tsx, so I changed it to a Page wrapper and everything seems to work again. 

Video: 

https://user-images.githubusercontent.com/18511823/188725099-32838f1e-88d2-4679-bb33-d2849aaf8315.mov

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] Feature flagged, if applicable

### CODE REVIEW

**Comment by wdoconnell** [comment]
@ChitlangeSahas Could you please test with a few of the pages involving multi-org content before we commit? I suspect the multi-org adjustment styles should be okay since it's only targeting children of the element with the class `multiOrg`, but could you double-check before we do? Thanks!

**Review by hoorayimhelping — APPROVED** [review]

**Review by wdoconnell — CHANGES_REQUESTED** [review]
Let's hold up for a moment, as this is impacting the multi-org style fixes. Posting a screenshot in a moment.

**Comment by wdoconnell** [comment]
Right now, the way we fix styles when the multiOrg header is on is to override clockface and reduce the total Page size by the current size of the global header `(calc 100% - gh.$globalheader-height)`. Right now, the fixes presume we don't have a 'page within a page', so a more general css selector like this is sufficient:

MultiOrgOverrideStyles.css
```
.multi-org .cf-page-contents > .ScrollbarsCustom-Wrapper {
  height: calc(100% - gh.$globalheader-height);
}
```

If we have a `<Page>` element outside of the existing `<Page>` element, we need to increase the selector specificity for the multi-org fixes, otherwise I think we're limiting the height 2x - first, by adjusting the window size for the first-level Page, then again for the second-level Page. For this to work with multi-Org I think we need to do something more like this:

MultiOrgOverrideStyles.css
```
.multi-org > [more specific selectors, so that we only adjust the second-level Page] > .cf-page-contents > .ScrollbarsCustom-Wrapper {
  height: calc(100% - gh.$globalheader-height);
}
```


Before changing the `div` to `Page`
--
Screen Shot 2022-09-06 at 4 00 57 PM

If we change the `div` to `Page` (bottom part cut off)
--
Screen Shot 2022-09-06 at 4 02 17 PM

**Comment by wdoconnell** [comment]
Re: interaction with multi-org styles, based on my testing it looks like we would still need the adjustment to page headers and notebooks. BUT it looks like we no longer need the custom adjustment to Page DapperScrollbars, Data Explorer, and Tasks if everything is wrapped in `<Page>`

**Review by hoorayimhelping — APPROVED** [review]

**Review by wdoconnell — APPROVED** [review]

**Comment by ALuckette** [comment]
nice work guys, good call making sure this works with multi-org.

**Pull request merged**
