### PR TITLE
fix: xDomain for scatter to be same as line

### PR DESCRIPTION
**Pull request by Palakp41**
Kapture 2020-10-07 at 10 08 33

### CODE REVIEW

**Review by Asalem1 — APPROVED** [review]
Great find!

**Comment by TCL735** [comment]
This might be in conflict with a recent change: https://github.com/influxdata/ui/pull/46

**Comment by 121watts** [comment]
@TCL735 can we rebase this with master and see it go green and then merge?

**Comment by TCL735** [comment]
@Palakp41 said it was indeed a conflict with a change that @drdelambre made, so i thought we weren't going to merge this.

**Comment by 121watts** [comment]
@Palakp41 @TCL735 should we close this?

**Pull request closed without merging**
