### PR TITLE
build: clone monitor-ci from deniz-slim-cypress-image branch

### PR DESCRIPTION
**Pull request by ebb-tide**

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 56 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

**Comment by genehynson** [comment]
@ebb-tide this still in use or can we close it?

**Comment by ebb-tide** [comment]
Still in use.
This is an attempt to use a slimmer version of the cypress image, but with
all the uncertainty around tests, this keeps getting deprioritized.

**Comment by Asalem1** [comment]
@ebb-tide is this still relevant / should we close this after the work that Gene is doing?

**Comment by ebb-tide** [comment]
I'm pretty sure this is already in with the work that @genehynson did

**Pull request closed without merging**
