### PR TITLE
feat: Accept yml and github directory locations

### PR DESCRIPTION
**Pull request by zoesteinkamp**
closes #19454
We now search for the github file from the directory. So for example the docker directory has a docker.yml file that we find and append to the url

### CODE REVIEW

**Comment by 121watts** [comment]
@zoesteinkamp you want to rebase this with master and see if it works?

**Comment by genehynson** [comment]
Do we still need this change @zoesteinkamp ?

**Comment by Asalem1** [comment]
@zoesteinkamp can this PR be closed?

**Comment by genehynson** [comment]
Closing this for now. If we find a need, we can always reopen it

**Pull request closed without merging**
