### PR TITLE
fix: default error message new github issue no longer puts hash as bug title

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Clicking on the link to create a bug from the error boundary created a bug with a non descriptive hash in the title. This puts it back to the way it used to be. It keeps the hash in the url, but it's not possible to do anything with it, yet.

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 39 | :red_circle:
accessibility | 87 | :green_circle:
best-practices | 87 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:

**Comment by russorat** [comment]
Why not put the entire bug template text in the url along with the text. You could then attach the version number (and whatever other stuff you wanted to the body. for example, try the link below. it has a slug for VERSION_HERE where you could dynamically add the version number to help debug. Github has docs here: https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

Also, we can make whatever text we want (we can make it shorter). This is just a urlencoded version of our current bug report template.

Thank%20you%20for%20reporting%20a%20bug%20in%20InfluxData%20UI.%0A%0A-%20Please%20ask%20usage%20questions%20on%20the%20Influx%20Community%20site.%0A%20%20-%20https%3A%2F%2Fcommunity.influxdata.com%2F%0A-%20Please%20add%20a%20%3A%2B1%3A%20or%20comment%20on%20a%20similar%20existing%20bug%20report%20instead%20of%20opening%20a%20new%20one.%0A%20%20-%20https%3A%2F%2Fgithub.com%2Finfluxdata%2Fui%2Fissues%3Futf8%3D%25E2%259C%2593%26q%3Dis%253Aissue%2Bis%253Aopen%2Bis%253Aclosed%2Bsort%253Aupdated-desc%2Blabel%253Akind%252Fbug%2B%0A-%20Please%20check%20whether%20the%20bug%20can%20be%20reproduced%20with%20the%20latest%20release.%0A-%20The%20fastest%20way%20to%20fix%20a%20bug%20is%20to%20open%20a%20Pull%20Request.%0A%20%20-%20https%3A%2F%2Fgithub.com%2Finfluxdata%2Fui%2Fpulls%0A%0A%2A%2ASteps%20to%20reproduce%3A%2A%2A%0AList%20the%20minimal%20actions%20needed%20to%20reproduce%20the%20behavior.%0A%0A1.%20...%0A2.%20...%0A3.%20...%0A%0A%2A%2AExpected%20behavior%3A%2A%2A%0ADescribe%20what%20you%20expected%20to%20happen.%0A%0A%2A%2AActual%20behavior%3A%2A%2A%0ADescribe%20What%20actually%20happened.%0A%0A%2A%2AEnvironment%20info%3A%2A%2A%0A%0A-%20System%20info%3A%20Run%20%60uname%20-srm%60%20and%20copy%20the%20output%20here%0A-%20InfluxDB%20version%3A%20Run%20%60influxd%20version%60%20and%20copy%20the%20output%20here%0A-%20Other%20relevant%20environment%20details%3A%20Container%20runtime%2C%20disk%20info%2C%20etc%0A%0A%2A%2AConfig%3A%2A%2A%0ACopy%20any%20non-default%20config%20values%20here%20or%20attach%20the%20full%20config%20as%20a%20gist%20or%20file.%0A%0A%3C%21--%20The%20following%20sections%20are%20only%20required%20if%20relevant.%20--%3E%0A%0A%2A%2ALogs%3A%2A%2A%0AInclude%20snippet%20of%20errors%20in%20log.%0A%0A%2A%2APerformance%3A%2A%2A%0AGenerate%20profiles%20with%20the%20following%20commands%20for%20bugs%20related%20to%20performance%2C%20locking%2C%20out%20of%20memory%20%28OOM%29%2C%20etc.%0A%0A%60%60%60sh%0A%23%20Commands%20should%20be%20run%20when%20the%20bug%20is%20actively.%0A%23%20Note%3A%20This%20command%20will%20run%20for%20at%20least%2030%20seconds.%0Acurl%20-o%20profiles.tar.gz%20%22http%3A%2F%2Flocalhost%3A8086%2Fdebug%2Fpprof%2Fall%3Fcpu%3Dtrue%22%0Acurl%20-o%20vars.txt%20%22http%3A%2F%2Flocalhost%3A8086%2Fdebug%2Fvars%22%0Aiostat%20-xd%201%2030%20%3E%20iostat.txt%0A%23%20Attach%20the%20%60profiles.tar.gz%60%2C%20%60vars.txt%60%2C%20and%20%60iostat.txt%60%20output%20files.%0A%60%60%60%0A%0AVersion%3A%20VERSION_HERE

**Review by russorat — CHANGES_REQUESTED** [review]
the url in this pr isn't a supported url param for creating github issues. see my other comment.

**Comment by hoorayimhelping** [comment]
>the url in this pr isn't a supported url param for creating github issues. see my other comment.

I know. I was trying to return to the previous behavior since this enhancement was a bust. I know that we can't use `version` currently, but it's not really an essential piece of information for a bug report, to be honest. It's nice to have, but not enough to blow out title.

I think string encoding the template is an interesting idea that I want to look into, for sure. BUT - I'd rather clean this up to make it usable and then make another small ticket to url encode the entire template. Since we haven't tried that before, if it doesn't work, it's a simple matter of rolling back to the good state. If we change it in one fell swoop and things don't work out, it'll be a little bit hairier getting back to the good state.

What do you think, @russorat ?

**Comment by russorat** [comment]
if that's the case, i would just use `https://github.com/influxdata/ui/issues/new?template=bug_report.md` as the url and forget the version url param. moving from one broken state to another broken state just doesn't feel right to me.

**Comment by hoorayimhelping** [comment]
NOW WITH EVEN FEWER NICE THINGS!

**Review by russorat — APPROVED** [review]
LGTM

**Pull request merged**
