### PR TITLE
chore: make annotation mode off by default, add note explaining xy plots only

### PR DESCRIPTION
**Pull request by hoorayimhelping**
- annotation write mode is toggled off by default
- shows a message saying we only support annotations on XY graphs

Screen Shot 2021-03-26 at 9 52 05 AM

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 40 | :red_circle:
accessibility | 96 | :green_circle:
best-practices | 93 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=993)

**Review by TCL735 — APPROVED** [review]

**Review by ChitlangeSahas — APPROVED** [review]

**Comment by daviddkkim** [comment]
Sorry for the late comment/
Could we try color: g13-mist for the "currently annotations only support ... " part ?

**Comment by hoorayimhelping** [comment]
@daviddkkim 
Screen Shot 2021-03-26 at 1 26 31 PM

**Comment by daviddkkim** [comment]
Looks good !!

**Review by daviddkkim — APPROVED** [review]
lgtm

**Pull request merged**
