### PR TITLE
test: enables notification tests, fixes failures

### LINKED ISSUE #153: Turn on testing for notifications
We have a big ole suite of tests that aren't getting run for notificationRules and notificationEndpoints.

We wanna turn them back on?

We wanna turn them back on!

blocked by:
influxdata/idpe#8268

### PR DESCRIPTION
**Pull request by genehynson**
Closes #153 

Enables notification e2e tests and changes test ids to correctly identify input fields.

Screen Shot 2020-12-15 at 11 38 26 AM
Screen Shot 2020-12-15 at 1 55 56 PM

- [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [x] Rebased/mergeable
- [x] Tests pass

### CODE REVIEW

**Comment by drdelambre** [comment]
what happened to that yarn.lock?!

**Comment by genehynson** [comment]
> what happened to that yarn.lock?!

huh no idea. Cleaned it up 😄

**Review by drdelambre — APPROVED** [review]
super cool. wait for https://github.com/influxdata/monitor-ci/pull/141 to merge before merging this one in

**Comment by drdelambre** [comment]
i think that PR is also why tests aren't passing

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 25 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | 22 | :red_circle:

**Pull request merged**
