### PR TITLE
fix: allow alerts with imports

### PR DESCRIPTION
**Pull request by drdelambre**
when trying to reproduce this one: https://github.com/influxdata/ui/issues/3919
i found out that our imports are all messed up, and if you try  to use a query that implements an import, we just fail silently
this normalizes the imports for the task generation mechanisms and combines them with the user defined  query's imports

### CODE REVIEW

**Comment by drdelambre** [comment]
a quick header hotfix snuck in here because i forgot how to change branches. lemme know if it's ok or if it's all too too much

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 55 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=4010)

**Review by asalem1 — APPROVED** [review]
Nice job guarding the buttons

**Comment by drdelambre** [comment]
too early to tell, but something crazy is going on with the interaction numbers... 3 times as many people are interacting with the query builder?
Screenshot 2022-03-07 9 41 46 AM

**Pull request merged**
