### PR TITLE
fix: Missing comma on tickscript.join - Fixed

### PR DESCRIPTION
**Pull request by Xoffio**
Missing comma added on `tickscript.join` function.

If you `Inject` the function `tickscript.join` on the ui. You will get the next error:

```
compilation failed: error @19:6-23:2: expected comma in property list, got COLON

error @21:7-21:18: missing property key 
```

### CODE REVIEW

**Comment by SpaceComet** [comment]
@asalem1 Done ! :)

**Review by asalem1 — APPROVED** [review]
Sorry for the delay. This looks good to me! I'd suggest merging / rebasing master into your branch to kick start the CI tests one last time since it looks like there's a failure that _should_ have been resolved since then. Thanks again for your contributions!!

**Review by SpaceComet — COMMENTED** [review]
re submit

**Comment by SpaceComet** [comment]
Hah that comma does not want to be in that file... I just tried gain and it felt. I don't know why is falling

**Comment by asalem1** [comment]
> Hah that comma does not want to be in that file... I just tried gain and it felt. I don't know why is falling

that's super weird. Let me give it a shot on a different branch

**Comment by asalem1** [comment]
> Ok! let me know if you need me to do anything :)

Ok, after some investigating, it looks like there are some tests that are dependent on the previous approach. It would be good to get @blegesse-git to verify whether the test failures are valid, or if the tests should be updated.

**Comment by asalem1** [comment]
@rockstar any chance you can take a look at this? It looks good from my perspective but maybe the test failures are indicative of something else

**Comment by rockstar** [comment]
Wow, this has been around for a bit. @Xoffio, really sorry I missed that @asalem1 asked me to look at this for so long. Could I have you rebase your changes on the most recent HEAD?

**Comment by wiedld** [comment]
@Xoffio -- apologies this never got in. We have resolved our process for running CI on forked PRs.

Looks like your branch requires a rebase. Please update, and I'll run this through CI. Thanks for your patience!

**Review by wiedld — APPROVED** [review]

**Pull request merged**
