### PR TITLE
feat: install UserPilot as a Walkme replacement

### PR DESCRIPTION
**Pull request by mavarius**
Installs UserPilot to the application as a replacement for Walkme.

### CODE REVIEW

**Review by drdelambre — APPROVED** [review]

**Comment by hoorayimhelping** [comment]
does anything from walkme need to be removed?

**Comment by mavarius** [comment]
@hoorayimhelping Not yet, we've disabled Walkme for now but we'll remove it once we get UserPilot working.

**Comment by mavarius** [comment]
Related: https://github.com/influxdata/design-resources/issues/25

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 41 | :red_circle:
accessibility | 96 | :green_circle:
best-practices | 93 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1081)

**Pull request merged**
