### PR TITLE
feat: add InfluxQL query composition

### LINKED ISSUE #6630: Add InfluxQL query composition

### PR DESCRIPTION
**Pull request by appletreeisyellow**
Closes #6630 

This PR adds basic InfluxQL query composition. Note that date picker for timestamp will be implemented in another PR tracked with https://github.com/influxdata/ui/issues/6653

## After

https://user-images.githubusercontent.com/14298407/225121144-428d1559-a3aa-4a05-98a5-c315a3d9fe3d.mov

All the work is behind the feature flag `influxqlUI`. 

To test on local remocal:
1) create DBRP mappings in your org ([instruction](https://github.com/influxdata/idpe/issues/17205)), and 
2) also make sure to turn on the following flags in your browser:
* `showOldDataExplorerInNewIOx`
* `newDataExplorer`
* `schemaComposition`

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [x] Feature flagged, if applicable

### CODE REVIEW

**Comment by appletreeisyellow** [comment]
CircleCI is having an outage so all CI tests failed. I will make the PR ready for review once CircleCI is back and CI tests become green.

**Comment by wdoconnell** [comment]
Looks good - but does this need to be feature flagged in any way?

**Comment by appletreeisyellow** [comment]
@wdoconnell Yeah, it is behind the feature flag `influxqlUI`

**Comment by wdoconnell** [comment]
Gotcha, thanks @appletreeisyellow

**Review by wdoconnell — APPROVED** [review]
Looks good. Are any of the `todo - add timestamps` necessary at the moment?

**Comment by appletreeisyellow** [comment]
> Are any of the todo - add timestamps necessary at the moment?

@wdoconnell Not for this PR. Those TODOs will be implemented in another PR tracked in https://github.com/influxdata/ui/issues/6653

**Pull request merged**
