### PR TITLE
test: nuclear option - shutting off annotations tests for now

### PR DESCRIPTION
**Pull request by hoorayimhelping**

### CODE REVIEW

**Review by TCL735 — APPROVED** [review]

**Comment by TCL735** [comment]
💥

**Review by genehynson — CHANGES_REQUESTED** [review]
lets debug the failure in our pipeline first. Deployments can disable the annotations tests in IDPE CI for now. But I'm afraid the current failure in our CI might be because of broken functionality

**Review by genehynson — COMMENTED** [review]
it's still my recommendation to try and understand why the test `can add and then delete a range annotation for the single stat + line graph` is failing consistently before we turn off all the tests, but I'll leave it up to you to decide

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 53 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2005)

**Review by genehynson — COMMENTED** [review]
github accept my review plz

**Review by genehynson — APPROVED** [review]
ok guess I have to approve it to make github happy lol

**Pull request merged**
