### PR TITLE
chore: bumps immer to 7.0.15

### PR DESCRIPTION
**Pull request by genehynson**
Yet another bump along the journey to getting immer to latest

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 52 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=1706)

**Review by Asalem1 — APPROVED** [review]
Are any of these hitting production and being tested?

**Comment by genehynson** [comment]
> Are any of these hitting production and being tested?

Yeah I'm clicking around in staging and testing them out. Seems fine 🤷

**Comment by Asalem1** [comment]
> > Are any of these hitting production and being tested?
> 
> Yeah I'm clicking around in staging and testing them out. Seems fine 🤷 I'm curious when I'm gonna hit the issue I was having with v8

Can we hold off on merging this until tomorrow just in case?

**Comment by Asalem1** [comment]
Just a heads up, it looks like the previous bump failed to land onto production so it might be worth kicking that up and pointing & clicking prior to getting this in

**Pull request merged**
