### PR TITLE
chore: upgrade to giraffe 2.15.7 to fix memory leak in PlotEnv

### PR DESCRIPTION
**Pull request by hoorayimhelping**
https://github.com/influxdata/giraffe/releases/tag/v2.15.7

### CODE REVIEW

**Review by genehynson — APPROVED** [review]

**Review by TCL735 — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 46 | :red_circle:
accessibility | 72 | :yellow_circle:
seo | 67 | :yellow_circle:
pwa | null | :hankey:
best-practices | 75 | :yellow_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

**Comment by genehynson** [comment]
> Metric	Score	Level
> performance	46	🔴
> accessibility	72	🟡
> seo	67	🟡
> pwa	null	💩
> best-practices	75	🟡
> [Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

yikes. @hoorayimhelping can you re-run the `cloud-lighthouse` job and make sure these numbers aren't real?

**Comment by hoorayimhelping** [comment]
> > Metric	Score	Level
> > performance	46	🔴
> > accessibility	72	🟡
> > seo	67	🟡
> > pwa	null	💩
> > best-practices	75	🟡
> > [Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)
> 
> yikes. @hoorayimhelping can you re-run the `cloud-lighthouse` job and make sure these numbers aren't real?

@genehynson looks like a fluke:
Screen Shot 2021-06-30 at 10 00 31 AM


https://20966-216092618-gh.circle-artifacts.com/0/tmp/results.html

**Comment by genehynson** [comment]
> > > Metric	Score	Level
> > > performance	46	🔴
> > > accessibility	72	🟡
> > > seo	67	🟡
> > > pwa	null	💩
> > > best-practices	75	🟡
> > > [Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)
> > 
> > 
> > yikes. @hoorayimhelping can you re-run the `cloud-lighthouse` job and make sure these numbers aren't real?
> 
> @genehynson looks like a fluke:
> Screen Shot 2021-06-30 at 10 00 31 AM
> 
> https://20966-216092618-gh.circle-artifacts.com/0/tmp/results.html

awesome, thanks for checking!

**Pull request merged**
