### PR TITLE
feat: implement add telegraf configuration from a Plugin page

### LINKED ISSUE #1555: Telegraf Refresh: Add Bucket--From Plugin, Create Mode
GIVEN that a user is on the `Load Data` page,
WHEN the user selects `Add Plugin to New Config` CTA from any of the available Telegraf plug-ins,
Then the user is taken to a modal where the user can optionally name the new configuration file AND
the user can select a bucket from the user's available buckets from a dropdown list

https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=263%3A337

### PR DESCRIPTION
**Pull request by TCL735**
Closes #1555 

Allows the user to add a telegraf configuration from a plugin's page, including creating a new bucket. NOTE: the actual text for the plugin's configuration is a separate issue and will be added later. The work here is to put up the frame so that we can fill in more pieces later.

https://user-images.githubusercontent.com/10736577/129282389-7b3d41a1-f033-4019-bb13-d5f3ba90a501.mp4

### CODE REVIEW

**Review by daviddkkim — CHANGES_REQUESTED** [review]
@TCL735  

Clockface Overlay's have a structure like this
<Overlay visible={true}>
  <Overlay.Container maxWidth={600}>
    <Overlay.Header />
    <Overlay.Body>
      // Contents go here
    </Overlay.Body>
    <Overlay.Footer>
      // Action buttons go here
    </Overlay.Footer>
  </Overlay.Container>
</Overlay>

If it isn't used that way, it will have inconsistent spacing between content in the overlay.

**Review by ChitlangeSahas — APPROVED** [review]
I pulled it down as well, it works as intended, looks good to me :)

**Comment by TCL735** [comment]
> @TCL735
> 
> Clockface Overlay's have a structure like this
> 
> <Overlay.Container >
> <Overlay.Header />
> <Overlay.Body>
> // Contents go here
> </Overlay.Body>
> <Overlay.Footer>
> // Action buttons go here
> </Overlay.Footer>
> </Overlay.Container>
> 
> If it isn't used that way, it will have inconsistent spacing between content in the overlay.

Thanks for the insight! I will fix the issue by pulling `<OverlayFooter />` out of the body

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2352)

**Pull request merged**
