### PR TITLE
chore: skip flakey tests until flag setting works

### PR DESCRIPTION
**Pull request by Asalem1**

### CODE REVIEW

**Review by drdelambre — APPROVED** [review]
why are we still having issues with feature flags?

**Comment by Asalem1** [comment]
> why are we still having issues with feature flags?

I'm trying to figure that out as we speak. I noticed this with some of the other feature flags where if a flag isn't set in the `test/local.libsonnet` file in KIND repo, then the flag doesn't get set all the time. The reason I'm not setting the local.libsonnet file with the feature flag is because that would affect the shared/about tests that should not have this feature

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 52 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=1975)

**Comment by genehynson** [comment]
just a heads up that @wojciechka is actively refactoring how we skip tests to make it easier: https://github.com/influxdata/idpe/pull/11199

**Comment by Asalem1** [comment]
> just a heads up that @wojciechka is actively refactoring how we skip tests to make it easier: [influxdata/idpe#11199](https://github.com/influxdata/idpe/pull/11199)

awesome, thanks for the heads up

**Pull request merged**
