### PR TITLE
chore: remove annotations and rangeAnnotations flags and checks

### LINKED ISSUE #2261: Annotations: Remove flags
### Background
Annotations is on in Prod and humming along nicely. It's time to remove the feature flagging code and just have annotations 

### Acceptance Criteria
- [ ] flagging conditions are remove
- [ ] `annotations`, `rangeAnnotations` are removed from flags.yml
- [ ] `annotations`, `rangeAnnotations`, are removed from config cat

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #2261

what it says on the tin

### CODE REVIEW

**Review by TCL735 — APPROVED** [review]

**Review by ChitlangeSahas — APPROVED** [review]

**Comment by genehynson** [comment]
can we update the tests too plz?

**Comment by hoorayimhelping** [comment]
@genehynson thanks. which configcat config does cypress get its flags from?

**Comment by genehynson** [comment]
> @genehynson thanks! which configcat config does cypress get its flags from?

it doesn't use config cat, just sets them directly to the redux state. So I think all you need to do is remove the `cy.setFeatureFlags` usage

**Review by genehynson — APPROVED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2306)

**Comment by Asalem1** [comment]
> @genehynson thanks! which configcat config does cypress get its flags from?

it gets the feature flags from the k8s-idpe feature flags list

**Pull request merged**
