### PR TITLE
fix: misc notebook bugs

### LINKED ISSUE #1414: notebooks: unusable functionality
1. stale state in query builder
Peek 2021-05-13 09-41

 1. query builder losing state (might be related to preview mode?)
Screenshot from 2021-05-13 09-44-52

 1. metric selector not filtering tag values correctly
Peek 2021-05-13 09-50

 1. whatever the heckers is going on with this time select dropdown
Peek 2021-05-13 09-53

### PR DESCRIPTION
**Pull request by drdelambre**
Closes #1414 

notebooks was in bad shape, mostly from stale updates clobbering each other in async calls. I sorted out a few of these by normalizing loading state and results away from source of truth for things like: query state, query builder cards' keys and values, some other things.

Also when i was running some graphs in tools to see how people were using notebooks... i found out that we couldn't see which panels people were deleting, so i added that in

Also, the metric selector filter logic was a bit weird after i touched it last. This one feels a lot better; it shows less stuff, but more accurately, making it more useful to search stuff

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 48 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=1423)

**Review by genehynson — COMMENTED** [review]
Looks good. But are there any tests we can add to prevent regressions on these state issues?

**Comment by drdelambre** [comment]
most of them expressed themselves by artificially introducing latency to the update cycles backed by network requests, but idk how to do that unobtrusively if this is the case
https://github.com/cypress-io/cypress-documentation/pull/512/files#diff-c27cf029e5d772fd7a01eaac074fe8cbdcd704823cf26c5e72df5f7618a8b950R122


any ideas?

**Comment by genehynson** [comment]
> any ideas?

Oh I see. Testing for latency sounds like a nightmare. I don't any ideas.

**Review by genehynson — APPROVED** [review]

**Pull request merged**
