### PR TITLE
build(lsp): Upgrade to flux-lsp-browser v0.6.2

### PR DESCRIPTION
**Pull request by rockstar**
Upgrade flux-lsp-browser to [v0.6.2](https://github.com/influxdata/flux-lsp/releases/tag/v0.6.2)

### CODE REVIEW

**Review by TCL735 — DISMISSED** [review]

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 62 | :yellow_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2444)

**Comment by drdelambre** [comment]
@rockstar can you rebase with master to kick this testing into working?

**Comment by genehynson** [comment]
> @rockstar can you rebase with master to kick this testing into working?

I looked into this - there are legitimate test failures regarding LSP stuff

**Comment by genehynson** [comment]
Closing in favor of: https://github.com/influxdata/ui/pull/2712

**Pull request closed without merging**
