### PR TITLE
build(lsp): Upgrade to flux-lsp-browser v0.5.41

### PR DESCRIPTION
**Pull request by scbrickley**
Upgrade flux-lsp-browser to [v0.5.41](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.41)

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 57 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1249)

**Review by drdelambre — APPROVED** [review]
anything we're expected to see change in this release?

**Comment by scbrickley** [comment]
Nothing major. Just importing the new version of Flux.

**Comment by scbrickley** [comment]
@drdelambre Could you bump this as well? Same change, just in OSS: https://github.com/influxdata/influxdb/pull/21267

**Pull request merged**
