### PR TITLE
fix: updating the docs links

### PR DESCRIPTION
**Pull request by russorat**
Similar to https://github.com/influxdata/influxdb/pull/20754

- [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
- [ ] Rebased/mergeable
- [ ] Tests pass

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 44 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | null | :question:

**Review by sanderson — APPROVED** [review]
Looks great 🚀

**Comment by genehynson** [comment]
@russorat I think you'll need to update this: https://github.com/influxdata/ui/blob/update-docs-links/cypress/e2e/shared/checks.test.ts#L554

**Comment by Asalem1** [comment]
@russorat might need to merge in the latest master to get those to tests to pass

**Comment by genehynson** [comment]
@russorat I rebased this again in case you still want to merge it

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=700)

**Comment by russorat** [comment]
@genehynson wanna give me a review?

**Review by genehynson — APPROVED** [review]

**Pull request merged**
