### PR TITLE
feat: remove example section from flux function's flyover panel 

### LINKED ISSUE #3106: Flux Dynamic Help Panels: remove the examples
As a user of the Script Editor, I do **_not_** want to see an example in the flyover panel for any Flux function. This may be part of a larger restructuring.

flux_function_example_code_remove

### PR DESCRIPTION
**Pull request by blegesse-git**
Closes #3106 

As part of the Flux Dymanic Help Panels epic, we are removing the example section and category from the script editor's flux function flyover panel. This change is behind a feature flag `influx.toggle('fluxDynamicDocs')`

Script Editor when feature flag is off: 
Screen Shot 2021-12-14 at 12 25 21 PM

Script Editor when feature flag is on: 
Screen Shot 2021-12-14 at 12 25 46 PM

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 51 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3434)

**Comment by TCL735** [comment]
This seems like a lot of work just to remove the example code under a feature flag.

**Comment by TCL735** [comment]
I will approve this for now, as there may be a simpler solution later.

**Review by TCL735 — APPROVED** [review]

**Comment by blegesse-git** [comment]
> @TCL735 
so this pr is removing example and function category. (i was going to remove the categories in a new pr but decided to combine them. I'll add this info in the pr description). Script Editor of Data Explorer is organized is in this manner: we have the TimeMachine folder which holds the `FluxToolbar` component. Inside FluxToolbar, the UI serves the `fluxFunctionsToolBar` folder which is where all the info used in the flyover panel comes from.  Inside fluxFunctionsToolBar, we have functions, arguments, description, example, and tooltip components. What I did in this pr is, inside `FluxToolbar.tsx`, I added an if statement that checks if the fluxdynamicdocs feature flag is on. If true, we serve a new folder titled `dynamicFluxFunctionsToolbar`. this new folder is essentially the same folder as `fluxFunctionsToolbar` except, it doesn’t contain TooltipExample component AND has logic that removes function category from being shown in the UI.

**Pull request merged**
