### PR TITLE
chore: lazy load monaco

### LINKED ISSUE #320: Lazy load monaco
Monaco takes a huge chunk of our bundle, for an interaction that is pretty buried in the application's UX. To help speed up the site and reduce the amount of time spent parsing JS on the initial load, lets lazy load it to get it out of that initial request!

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #320 

So, the solution here was pretty straightforward. I updated the webpack plugin to exclude certain features from the monaco editor. Here's a list of the available features:

```
['accessibilityHelp', 'anchorSelect', 'bracketMatching', 'caretOperations', 'clipboard', 'codeAction', 'codelens', 'colorDetector', 'comment', 'contextmenu', 'coreCommands', 'cursorUndo', 'dnd', 'find', 'folding', 'fontZoom', 'format', 'gotoError', 'gotoLine', 'gotoSymbol', 'hover', 'iPadShowKeyboard', 'inPlaceReplace', 'indentation', 'inspectTokens', 'linesOperations', 'links', 'multicursor', 'onTypeRename', 'parameterHints', 'quickCommand', 'quickHelp', 'quickOutline', 'referenceSearch', 'rename', 'smartSelect', 'snippets', 'suggest', 'toggleHighContrast', 'toggleTabFocusMode', 'transpose', 'unusualLineTerminators', 'viewportSemanticTokens', 'wordHighlighter', 'wordOperations', 'wordPartOperations']
```

Truthfully I wasn't sure which ones we were using or not so I just went down and looked for the ones that stood out as obvious like `comment` and `bracketMatching`

I couldn't find any info besides the source code on what each of these features does, and even then it wasn't clear so I'm happy to revisit what's being excluded.

Here's a screenshot of what the bundle size was before the change:

Screen Shot 2020-12-15 at 2 40 39 PM

Here's a screenshot of the bundle size after the change:

Screen Shot 2020-12-15 at 3 29 06 PM

### CODE REVIEW

**Comment by drdelambre** [comment]
it's good to see a smaller bundle, but this doesn't close the issue right?

**Comment by 121watts** [comment]
yeah, there's no lazy loading here.  the reduction in bundle size is exclusively from the removing of unused monaco features.

**Review by 121watts — CHANGES_REQUESTED** [review]
let's do the lazy loading too.  then, I would love to see a screenshot of the difference in bundle size served to page that doesn't use monaco i.e. `GettingStarted`

**Comment by drdelambre** [comment]
should make every page faster right? i dont think any default with showing monaco

**Comment by Asalem1** [comment]
Here's what the loading state looks like:

loading-state

Loading Time With Lazy Loading:
Screen Shot 2020-12-16 at 10 37 20 AM

Loading Time Without Lazy Loading:
Screen Shot 2020-12-16 at 10 39 54 AM

**Review by 121watts — APPROVED** [review]
So excited!  It's happening

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 33 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 87 | :green_circle:
seo | 80 | :yellow_circle:
pwa | 22 | :red_circle:

**Pull request merged**
