### PR TITLE
build: upgrade flux-lsp-browser to v0.5.23

### PR DESCRIPTION
**Pull request by scbrickley**
Upgrade to [Flux LSP v0.5.23](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.23)

### CODE REVIEW

**Comment by hoorayimhelping** [comment]
@scbrickley in the PR description, would you mind adding a link to the PR that this implements on the flux side please? that way we can link things more easily in the future

**Comment by scbrickley** [comment]
I can do that, but just to clarify, could you tell me if either of the following links are what you're looking for?

1. Flux LSP Release: https://github.com/influxdata/flux-lsp/releases/tag/v0.5.23
2. Flux Release: https://github.com/influxdata/flux/releases/tag/v0.95.0

Those aren't PRs, but they sum up all the changes that the new release includes. The PRs that increment the version may not be that helpful, as it's usually just version bump. The interesting stuff comes from all the PRs that are merged between each release.

Sorry if I'm misunderstanding.

**Comment by hoorayimhelping** [comment]
@scbrickley the one that's relevant to us is the flux lsp release that's being pulled in. https://github.com/influxdata/flux-lsp/releases/tag/v0.5.23.

ideally in the release notes, it would link back to what it's upgrading to (https://github.com/influxdata/flux/releases/tag/v0.95.0). all this information is findable, but it's just a little easier having lazy links for someone to follow.

imagine in 4 months we discover some weird flux bug and trace it back to this version of the library. we probably won't remember all the details of what we changed today, in 4 months, so having information we can go look at would help a lot in that situation.

**Comment by scbrickley** [comment]
All good points. I'll add the relevant links to the PR + release notes.

**Review by hoorayimhelping — APPROVED** [review]

**Pull request merged**
