### PR TITLE
chore: add Heap analytics

### PR DESCRIPTION
**Pull request by peterbarnett03**
This is re-enabling some UX analytics software so we can better understand usage patterns for future UI/UX updates across the InfluxData suite of products.

### Checklist

Authors and Reviewer(s), please verify the following:

- [X] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [X] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [X] Documentation updated or issue created (provide link to issue/PR)
- [X] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [X] Feature flagged, if applicable

### CODE REVIEW

**Comment by blegesse-w** [comment]
Hi @peterbarnett03, I'll prioritize this and take a look at it today. In the meantime, do you know why the monitor-ci job is failing? Haven't had a chance to investigate

**Review by blegesse-w — COMMENTED** [review]
Hi @peterbarnett03, I'll prioritize this and take a look at it today. In the meantime, do you know why the monitor-ci job is failing? Haven't had a chance to investigate

**Comment by wdoconnell** [comment]
I'll pick this one up as part of the internal ticket we have for this. I think the CI failure is related to the mon ci runner changes we made recently so I can take a look. 👍

**Comment by wdoconnell** [comment]
@blegesse-w @peterbarnett03 This should be ready for a re-review. I added a few things here to what Pete already included:

1. Moved the heap identifiers to a ConfigCat int flag so that they stay out of code, and so we can control the staging/production identifiers through ConfigCat.
2. Cleans up the window object and script tags if the script fails.
3. Added some explanatory comments where necessary.

Overall I didn't see any regressions in behavior when I tested it local. This is less temperamental than the VWO script and the fetched scripts don't appear to interfere with page styles.

**Review by peterbarnett03 — COMMENTED** [review]
LGTM -- appreciate you moving the ID to a dynamic flag.

**Review by blegesse-w — APPROVED** [review]
this looks good to me. Anything else needs to be in place before merging?

**Comment by wdoconnell** [comment]
> this looks good to me. Anything else needs to be in place before merging?

Pending a final approval in https://github.com/influxdata/granite/issues/3358.

**Review by abshierjoel — APPROVED** [review]

**Comment by wdoconnell** [comment]
CircleCI status page indicates jobs are failing. I'll wait until those resolve before re-merging.

**Pull request merged**
