### PR TITLE
feat: display ids of alerts, notification endpoints, and notification rules

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Connects #1169

- Show ids and allow copying of ids for Alerts, Notification Endpoints, and Notification Rules (similar to tasks).
- Allow filtering of Alerts, Notification Endpoints, Notification Rules, and Tasks by id.

https://user-images.githubusercontent.com/146112/114471867-23a7ad80-9ba6-11eb-8857-01cda5ea6641.mov

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=1185)

**Comment by russorat** [comment]
I'm assuming that is the ID of the check and not the ID of the task that powers the check, right?

**Comment by hoorayimhelping** [comment]
>I'm assuming that is the ID of the check and not the ID of the task that powers the check, right?

@russorat  correct. getting the underlying task is the next step and might take some doing.

**Review by Palakp41 — APPROVED** [review]
Looks great :)

**Pull request merged**
