### PR TITLE
chore: do not escape backslashes in measurements and fields regex

### PR DESCRIPTION
**Pull request by subirjolly**
Closes https://github.com/influxdata/data-acquisition/issues/403

Currently, we are adding extra complexity and confusion by replacing `\\` to be `\` in a regular expression. We don't need it, thus removing the functionality.

### Checklist

Authors and Reviewer(s), please verify the following:

- [x] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [x] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [x] Documentation updated or issue created (provide link to issue/PR)
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ ] Feature flagged, if applicable

### CODE REVIEW

**Review by genehynson — APPROVED** [review]

**Comment by genehynson** [comment]
Can we update the hint text in the textboxes too? Right now the example has two slashes `\\`

**Comment by subirjolly** [comment]
> Can we update the hint text in the textboxes too? Right now the example has two slashes `\\`

Done!

**Comment by helenosheaa** [comment]
can you also update the regex timestamp line 82, i somehow just noticed it says: placeholder="eg. regexExample"

**Review by genehynson — APPROVED** [review]

**Review by helenosheaa — APPROVED** [review]
great, thanks!

**Pull request merged**
