### PR TITLE
fix: use threshold settings from shared/components

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
Closes https://github.com/influxdata/ui/issues/879

I hypothesize that we were using the outdated `ThresholdSettings` code. Using different import from `'src/shared/components/ThresholdsSettings'` seems to fix it. 

- [ ] [E2E Tests pass in k8s-idpe](https://docs.influxdata.io/development/guides/local-development/#three-ways-to-run-the-ui-e2e-tests-against-the-kind-cluster) (applicable only if you edited Cypress tests)

### CODE REVIEW

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 28 | :red_circle:
accessibility | 96 | :green_circle:
best-practices | 93 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :question:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=916)

**Comment by drdelambre** [comment]
lemme see where else we're using that file

**Comment by genehynson** [comment]
> Metric	Score	Level
> performance	28	🔴
> accessibility	96	🟢
> best-practices	93	🟢
> seo	90	🟢
> pwa	null	❓
> [Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?vars%5Blighthouse_score_branch%5D=916)

I'm concerned that the performance scored dropped to 28?? It was hovering above 40...

**Comment by ChitlangeSahas** [comment]
I see that now, I wonder why that would be the case!

**Review by drdelambre — CHANGES_REQUESTED** [review]
gonna ask that you flip that movement. even though the component is in src/shared, it seems like it's not shared with anything?

so it'd make more sense to just `git mv` the shared version into src/visualization

seems like a trivial distinction, but by keeping the code collocated, you group concepts in another dimension to reenforce encapsulation, hopefully curtailing arbitrary reuse and preventing the spaghetti from popping back out again

*all claims dictated, not read, and with no guarantee they were made with a complete view of ramifications

**Comment by genehynson** [comment]
> I see that now, I wonder why that would be the case!

looks like it was a flake - rerun brings it back to 41

**Review by drdelambre — APPROVED** [review]

**Pull request merged**
