### PR TITLE
tweaking layout with names

### LINKED ISSUE #3172: tweak layout of existing schema 'editing panel' in the bucket schema advanced section
change to: 

was:

(note how the alignment is skewed from a long name)

minor change, will need minor e2e test changes as well

### PR DESCRIPTION
**Pull request by jrenee42**
Closes #3172 

original:
Screen Shot 2021-11-08 at 2 56 31 PM

new one:

Screen Shot 2021-11-09 at 11 29 45 AM

### CODE REVIEW

**Comment by ChitlangeSahas** [comment]
Looks good to me! 

Small visual comment, if I were to vote for a design, it would be to eliminate the "Name" part entirely, and have the name of the schema just show. 

Instead of `Name: name of the schema`, `Name of the schema` .

It's just an opinion, @daviddkkim thoughts on this?

**Review by ChitlangeSahas — APPROVED** [review]
Meant to approve it the first time around.

**Comment by daviddkkim** [comment]
I actually agree with @ChitlangeSahas on that - I think we can just write the name of the schema instead of name: schema. That would help w things being less cluttered

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 60 | :red_circle:
accessibility | 97 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 93 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=3176)

**Pull request merged**
