### PR TITLE
fix: remove aggregate window

### PR DESCRIPTION
**Pull request by drdelambre**
people dont understand it and some get angry at it

closes: #2843

### CODE REVIEW

**Comment by genehynson** [comment]
Issue #2843 right?

**Comment by drdelambre** [comment]
i dont understand 1, but you're both right about the other things

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 54 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2886)

**Review by genehynson — APPROVED** [review]
all the red!

**Pull request merged**
