### PR TITLE
chore: undo resizing of the markdown

### LINKED ISSUE #2070: Notebook: Change the Markdown panel back to autosize
We recently decided to make several panels, including the markdown panel, resizeable. After interacting with a notebook including several markdown panels, it's clear that it is more of a hindrance to the user experience than an advantage to have a markdown panel with a resizer and set height. Since we can't have a resizer without including a set height vs. autosize height, we would like to prioritize the autosize height and get rid of the resizer.

### PR DESCRIPTION
**Pull request by Asalem1**
Closes #2070 

Reenables autosizing of the markdown panel

### CODE REVIEW

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 59 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=2266)

**Review by drdelambre — APPROVED** [review]

**Comment by drdelambre** [comment]
Eait

**Comment by drdelambre** [comment]
Wait* you have to add the autosize prop back to the Monaco editor instance

**Comment by Asalem1** [comment]
> Wait* you have to add the autosize prop back to the Monaco editor instance

Not sure if that's what you meant or if you wanted the `resizes` prop tacked on. I did that before and it caused a bunch of weird styling issues, felt wrong to conditionally set it but 🤷🏽

**Comment by drdelambre** [comment]
can i double approve?

**Pull request merged**
