### PR TITLE
chore: removing annotations control bar, adding info to the hover tit…

### PR DESCRIPTION
**Pull request by daviddkkim**
removing annotations control bar, adding info to the hover title text on the annotation button. Removing related tests

Closes #

https://user-images.githubusercontent.com/12561526/123492841-828a9980-d5cf-11eb-91af-7f2f9c38d513.mp4

### CODE REVIEW

**Comment by daviddkkim** [comment]
I didn't actually remove the code for the annotations bar. I can if yall are okay with that

**Review by hoorayimhelping — APPROVED** [review]

**Comment by TCL735** [comment]
> I didn't actually remove the file for the annotations bar. I can if yall are okay with that

Unused code should be removed

**Comment by daviddkkim** [comment]
> > I didn't actually remove the file for the annotations bar. I can if yall are okay with that
> 
> Unused code should be removed

on it

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 56 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 98 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=master)

**Review by jrenee42 — APPROVED** [review]

**Comment by daviddkkim** [comment]
Screen Shot 2021-06-28 at 1 05 35 PM

**Pull request merged**
