### PR TITLE
chore: add script to create oss releases

### PR DESCRIPTION
**Pull request by wbaker85**
This is a script that can be used to create/update releases for the OSS "Master" branch.

Eventually I'd like to automate the release process for the "Master" UI, but there's a few wrinkles I need to get sorted out. For now I'd like to put the script into the version control system so that it lives somewhere permanent.

### CODE REVIEW

**Comment by genehynson** [comment]
We still need this @wbaker85 ? If so, try rebasing the branch to get the CI to pass

**Comment by wbaker85** [comment]
Ah, kind of forgot about this, but yeah it'd be nice to get checked in. Obviously not super high priority :smile:. I just rebased it.

**Comment by ui-ci-bot-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 49 | :red_circle:
accessibility | 96 | :green_circle:
seo | 90 | :green_circle:
pwa | null | :hankey:
best-practices | 100 | :green_circle:


[Compare your scores with master branch](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/073c4b95f1089000?lower=now%28%29%20-%202d&vars%5Blighthouse_score_branch%5D=1389)

**Comment by genehynson** [comment]
@wbaker85 we had a fiasco with a failing test today - you'll want to rebase again to fix that on this branch 😅

**Review by genehynson — APPROVED** [review]

**Pull request merged**
